import type { Metadata } from "next";

import {ThemeProvider} from "@mui/material";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

import Header from "src/components/Header";
import theme from "src/theme";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">

      <body>
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
        <Header />

        {children}
        </ThemeProvider>
      </AppRouterCacheProvider>

      </body>
    </html>
  );
}
